name       : insomnia
version    : 2021.4.1
release    : 16
source     :
    - https://github.com/Kong/insomnia/archive/refs/tags/core@2021.4.1.tar.gz : 7286d57eefadda230f6ade9ca0778ad480e255741a10a22ef7e0368fc2cefb5e
license    : MIT
component  : programming.tools
summary    : HTTP/REST and GraphQL client
description: |
    Insomnia is a REST and GraphQL client built with Electron.
networking : yes
builddeps  :
    - pkgconfig(fontconfig)
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/Skip-Node-version-check.patch
    npm run bootstrap
build      : |
    export GIT_TAG=core@${version}
    npm run app-package
install    : |
    install -dm00755 $installdir/usr/share
    rm packages/insomnia-app/dist/linux-unpacked/LICENSE*
    cp -a packages/insomnia-app/dist/linux-unpacked $installdir/usr/share/insomnia
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
    install -Dm00644 packages/insomnia-app/app/static/insomnia-core-logo_16x.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm00644 $pkgfiles/insomnia.desktop -t $installdir/usr/share/applications
