name       : insomnia
version    : 2020.4.1
release    : 10
source     :
    - https://github.com/Kong/insomnia/archive/core@2020.4.1.tar.gz : fee98df2687ea87814bb9c71d387da30757c3b8ee143ab9cfb2e63c883ff93e8
license    : MIT
component  : programming.tools
summary    : HTTP/REST and GraphQL client
description: |
    Insomnia is a REST and GraphQL client built with Electron.
networking : yes
builddeps  :
    - pkgconfig(fontconfig)
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/Skip-Node-version-check.patch
    npm run bootstrap
build      : |
    export GIT_TAG=core@${version}
    npm run app-package
install    : |
    install -dm00755 $installdir/usr/share
    rm packages/insomnia-app/dist/com.insomnia.app/linux-unpacked/LICENSE*
    cp -a packages/insomnia-app/dist/com.insomnia.app/linux-unpacked $installdir/usr/share/insomnia
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
    install -Dm00644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm00644 $pkgfiles/insomnia.desktop -t $installdir/usr/share/applications
