name       : insomnia
version    : 5.12.4
release    : 1
source     :
    - https://github.com/getinsomnia/insomnia/archive/v5.12.4.tar.gz : 601bab30e5a04ffc97370c2e79889f64742d606e359ca9035601d66b87347661
license    : AGPL-3.0
component  : programming.tools
summary    : Insomnia is a cross-platform REST client
description: |
    Insomnia is a cross-platform REST client
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - lerna
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-Analytics-by-default.patch
build      : |
    npm install electron-builder
    export PATH=$PATH:$workdir/node_modules/.bin
    npm run bootstrap
    npm run app-build
    cd packages/insomnia-app/build
    electron-builder
install    : |
    install -Dm644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm644 $pkgfiles/insomnia.desktop $installdir/usr/share/applications/insomnia.desktop
    install -dm00644 $installdir/usr/share/insomnia
    install -dm00644 $installdir/usr/bin
    cp -R packages/insomnia-app/build/dist/linux-unpacked/* $installdir/usr/share/insomnia/
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
