name       : insomnia
version    : 5.14.7
release    : 2
source     :
    - https://github.com/getinsomnia/insomnia/archive/v5.14.7.tar.gz : 5fa0c34310226164e8030b872b5be4da66bd4072a2586805215b2f52322ab210
license    : AGPL-3.0
component  : programming.tools
summary    : Insomnia is a cross-platform REST client
description: |
    Insomnia is a cross-platform REST client
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - lerna
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-Analytics-by-default.patch
build      : |
    npm install electron-builder
    export PATH=$PATH:$workdir/node_modules/.bin
    npm run bootstrap
    npm run app-build
    cd packages/insomnia-app/build
    electron-builder --linux dir --x64
install    : |
    install -Dm644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm644 $pkgfiles/insomnia.desktop $installdir/usr/share/applications/insomnia.desktop
    install -dm00644 $installdir/usr/share/insomnia
    install -dm00644 $installdir/usr/bin
    cp -R packages/insomnia-app/build/dist/linux-unpacked/* $installdir/usr/share/insomnia/
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
