name       : insomnia
version    : 2020.3.3
release    : 9
source     :
    - https://github.com/Kong/insomnia/archive/core@2020.3.3.tar.gz : 82f3e7662944624ba45726e8ee9f776aa19b8f2a31f9767f2c2bc8ca0411844f
license    : MIT
component  : programming.tools
summary    : HTTP/REST and GraphQL client
description: |
    Insomnia is a REST and GraphQL client built with Electron.
networking : yes
builddeps  :
    - pkgconfig(fontconfig)
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/Skip-Node-version-check.patch
    npm run bootstrap
build      : |
    export GIT_TAG=core@${version}
    npm run app-package
install    : |
    install -dm00755 $installdir/usr/share
    rm packages/insomnia-app/dist/linux-unpacked/LICENSE*
    cp -a packages/insomnia-app/dist/linux-unpacked $installdir/usr/share/insomnia
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
    install -Dm00644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm00644 $pkgfiles/insomnia.desktop -t $installdir/usr/share/applications
