name       : insomnia
version    : 2021.1.0
release    : 12
source     :
    - https://github.com/Kong/insomnia/archive/core@2021.1.0.tar.gz : c8d61da817dadbf6da311b28fe6385372d7cc6fb4f4e80fdde8665b0897cd42a
license    : MIT
component  : programming.tools
summary    : HTTP/REST and GraphQL client
description: |
    Insomnia is a REST and GraphQL client built with Electron.
networking : yes
builddeps  :
    - pkgconfig(fontconfig)
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/Skip-Node-version-check.patch
    npm run bootstrap
build      : |
    export GIT_TAG=core@${version}
    npm run app-package
install    : |
    install -dm00755 $installdir/usr/share
    rm packages/insomnia-app/dist/linux-unpacked/LICENSE*
    cp -a packages/insomnia-app/dist/linux-unpacked $installdir/usr/share/insomnia
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
    install -Dm00644 packages/insomnia-app/app/static/insomnia-core-logo_16x.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm00644 $pkgfiles/insomnia.desktop -t $installdir/usr/share/applications
