name       : insomnia
version    : 6.0.2
release    : 5
source     :
    - https://github.com/getinsomnia/insomnia/archive/v6.0.2.tar.gz : 2b704ccf364560d41865982dedc0e07ec5ab9dd4ef565b30924fce7b58d8bfb9
license    : AGPL-3.0
component  : programming.tools
summary    : Insomnia is a cross-platform REST client
description: |
    Insomnia is a cross-platform REST client
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - lerna
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm run bootstrap
    npm install electron-builder
    npm run app-build
    cd packages/insomnia-app/build
    ../node_modules/.bin/electron-builder --linux dir --x64
install    : |
    install -Dm644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
    install -Dm644 $pkgfiles/insomnia.desktop $installdir/usr/share/applications/insomnia.desktop
    install -dm00644 $installdir/usr/share/insomnia
    install -dm00644 $installdir/usr/bin
    cp -R packages/insomnia-app/build/dist/linux-unpacked/* $installdir/usr/share/insomnia/
    ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
